version: "3.3"

services:
  server1:
    build:
      context: .
      dockerfile: server-dockerfile
    image: raft_fcul_server
    container_name: raft_fcul_server_1
    networks:
      - raft_fcul_network
    environment:
      - SERVERS=raft_fcul_server_1:raft_fcul_server_2:raft_fcul_server_3
      - LEADER=true
      - LEADER_NAME=raft_fcul_server_1
    env_file:
      - .env-server

  server2:
    build:
      context: .
      dockerfile: server-dockerfile
    image: raft_fcul_server
    container_name: raft_fcul_server_2
    networks:
      - raft_fcul_network
    environment:
      - SERVERS=raft_fcul_server_1:raft_fcul_server_2:raft_fcul_server_3
      - LEADER_NAME=raft_fcul_server_1
    env_file:
      - .env-server

  server3:
    build:
      context: .
      dockerfile: server-dockerfile
    image: raft_fcul_server
    container_name: raft_fcul_server_3
    networks:
      - raft_fcul_network
    environment:
      - SERVERS=raft_fcul_server_1:raft_fcul_server_2:raft_fcul_server_3
      - LEADER_NAME=raft_fcul_server_1
    env_file:
      - .env-server

  client:
    build:
      context: .
      dockerfile: client-dockerfile
    image: raft_fcul_client
    stdin_open: true
    tty: true
    networks:
      - raft_fcul_network
    environment:
      - SERVERS=raft_fcul_server_1:raft_fcul_server_2:raft_fcul_server_3
      - LEADER=raft_fcul_server_1
    env_file:
      - .env-client
    depends_on:
      - server1
      - server2
      - server3

networks:
  raft_fcul_network: